### PR TITLE
For derived values send nil on the first measurement

### PR DESCRIPTION
**Pull request by IzabellaRaulin**
Fixed  https://github.com/intelsdi-x/snap-plugin-collector-mysql/issues/15

Summary of changes:
- for derives and counters representing a rate of change send a nil on the first measurement (see [mysqlplugin/collector.go#L208] (https://github.com/IzabellaRaulin/snap-plugin-collector-mysql/blob/first_derived_value/mysqlplugin/collector.go#L208)
- for counters added the different behaviour when value<sub>new</sub> < value <sub>old</sub>; in such cases, there is an assumption that the counter “wrapped around” 

plus:
- added exemplary task manifest (collecting the whole set of metrics)
- updated Godeps to the latest snap
- fixed typo mistakes 

Testing done:
- unit tests
- test the following scenario:  
   - create a task (see [task manifest] (examples/tasks/task_all.json)),
  - start the task and observe that for the first measurement derives and counters equal `nil`.
  - stop the task
  - restart the task and verify that the first incoming values (for derives and counters) are `nil`

```
2016-07-08 17:03:19.444262146 +0200 CEST|/intel/mysql/mysql_commands/select|<nil>|tags[plugin_running_on:devmachine]
2016-07-08 17:03:20.449693252 +0200 CEST|/intel/mysql/mysql_commands/select|0.9944374055402553|tags[plugin_running_on:devmachine]
2016-07-08 17:03:21.457116414 +0200 CEST|/intel/mysql/mysql_commands/select|0.992476665613146|tags[plugin_running_on:devmachine]
2016-07-08 17:03:22.445790547 +0200 CEST|/intel/mysql/mysql_commands/select|1.011628651111959|tags[plugin_running_on:devmachine]

//here the task was stopped

2016-07-08 17:11:46.877977933 +0200 CEST|/intel/mysql/mysql_commands/select|<nil>|tags[plugin_running_on:iza-devmachine]
2016-07-08 17:11:47.926859027 +0200 CEST|/intel/mysql/mysql_commands/select|0.9519847789286142|tags[plugin_running_on:devmachine]
2016-07-08 17:11:48.924835886 +0200 CEST|/intel/mysql/mysql_commands/select|1.0022810644129085|tags[plugin_running_on:devmachine]
2016-07-08 17:11:49.882429386 +0200 CEST|/intel/mysql/mysql_commands/select|1.045587578698946|tags[plugin_running_on:devmachine]

```

@intelsdi-x/plugin-maintainers

### CODE REVIEW

**Comment by IzabellaRaulin** [comment]
@woodsaj, could You verify if that fixes your issue. Thank You.

**Comment by katarzyna-z** [comment]
I've been testing this pull request with snap-publisher-indluxdb and it seems that influxdb has a problem with `nil` as metric value : 
```
ID 					 NAME 						 STATE 		 HIT 	 MISS 	 FAIL 	 CREATED 		 LAST FAILURE
6558d895-ad57-47dd-a5ba-51304d49e5e6 	 Task-6558d895-ad57-47dd-a5ba-51304d49e5e6 	 Running 	 1 	 0 	 1 	 3:17PM 7-12-2016 	 Publish call error: {"error":"unable to parse 'intel/mysql/mysql_commands/select,source=kzab-Z97X-UD7-TH value= 1468329473': missing field value"}
```

After changing `nil` to `0` I'm receiving : 
```
ID 					 NAME 						 STATE 		 HIT 	 MISS 	 FAIL 	 CREATED 		 LAST FAILURE
c9c7c5d5-5d4f-4555-976c-1e419cb411b1 	 Task-c9c7c5d5-5d4f-4555-976c-1e419cb411b1 	 Running 	 2 	 0 	 1 	 3:05PM 7-12-2016 	 Publish call error: {"error":"write failed: field type conflict: input field \"value\" on measurement \"intel/mysql/mysql_commands/select\" is type float64, already exists as type integer"}
```

After changing `nil` to `0.0` task works without problems. 
It is because influxdb does not accept data type changes so as the first value of metric it should be send zero-value for the type of metric.

**Comment by woodsaj** [comment]
@IzabellaRaulin yes, this is working great for me.

@katarzyna-z:  Sending 0 will introduce the same sudden spikes/dips in graphs that this PR is intending to fix. Not accepting nil seems like a bug in the snap-publisher-influxdb plugin and you should open an issue there.

**Comment by katarzyna-z** [comment]
@woodsaj Good point, I'm investigating the issue which I noticed.
Where do you publish metrics? Did you use snap-plugin-publisher-influxdb? If yes, can you check version of the publisher plugin and version of Influxdb?

**Comment by woodsaj** [comment]
@katarzyna-z i use the snap-publisher-plugin-graphite

**Comment by katarzyna-z** [comment]
I confirmed that it is the issue in snap-plugin-publisher-influxdb. snap-plugin-publisher-influxdb always returns an error for "nil" value of metric. I'm opening the issue for influxdb publisher.

LGTM

**Pull request merged**
